Game-master/Game/Models/Gamer.cs
using System.ComponentModel.DataAnnotations;

public class Gamer
{
    public int Id { get; set; }
    [Required(ErrorMessage = "Некорректный ввод")]
    [RegularExpression(@"^[А-Яа-яЁё\s-]+$", ErrorMessage = "Некорректный ввод")]
    [Display(Name = "Фамилия")]
    public string? Surname { get; set; }

    [Required(ErrorMessage = "Некорректный ввод")]
    [RegularExpression(@"^[А-Я]+[а-яА-Я\s]*$", ErrorMessage = "Некорректный ввод")]
    [Display(Name = "Имя")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Некорректный ввод")]
    [DataType(DataType.Date)]
    [Display(Name = "Дата заказа")]
    public DateTime DataRegistr { get; set; }

    [Required(ErrorMessage = "Некорректный ввод")]
    [EmailAddress(ErrorMessage = "Некорректный ввод")]
    [Display(Name = "Почта")]
    public string? Email { get; set; }

    [Required(ErrorMessage = "Некорректный ввод")]
    [StringLength(100, MinimumLength = 11, ErrorMessage = "Некорректный ввод")]
    [DataType(DataType.Password)]
    [Display(Name = "Номер телефона")]
    public string? Paswd { get; set; }

    [Required(ErrorMessage = "Некорректный ввод")]
    [Display(Name = "Ранг остроты")]
    public string? Rank { get; set; }

    public ICollection<Character> Characters { get; set; } = new List<Character>();

}

Game-master/Game/Controllers/GamersController.cs
using Game.Data;
using Game.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace Game.Controllers
{
    public class GamersController : Controller
    {
        private readonly GameContext _context;

        public GamersController(GameContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string GamerRank, string searchString)
        {
            if (_context.Gamer == null)
            {
                return Problem("Entity set 'GameContext.Gamer' is null.");
            }

            IQueryable<string> rankQuery = from m in _context.Gamer
                                           orderby m.Rank
                                           select m.Rank;

            var gamersQuery = from m in _context.Gamer
                              select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                gamersQuery = gamersQuery.Where(s => s.Name.Contains(searchString) ||
                                                   s.Surname.Contains(searchString) ||
                                                   (s.Rank != null && s.Rank.Contains(searchString)));
            }

            if (!string.IsNullOrEmpty(GamerRank))
            {
                gamersQuery = gamersQuery.Where(x => x.Rank == GamerRank);
            }

            var GamerRankVM = new GamerRankViewModel
            {
                Rank = new SelectList(await rankQuery.Distinct().ToListAsync()),
                Gamers = await gamersQuery.ToListAsync(),
                GamerRank = GamerRank,
                SearchString = searchString
            };

            return View(GamerRankVM);
        }

        // GET: Gamers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamer = await _context.Gamer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gamer == null)
            {
                return NotFound();
            }

            return View(gamer);
        }

        // GET: Gamers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Gamers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,Name,DataRegistr,Email,Paswd,Rank")] Gamer gamer)
        {
           // if (ModelState.IsValid)
            {
                _context.Add(gamer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gamer);
        }

        // GET: Gamers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamer = await _context.Gamer.FindAsync(id);
            if (gamer == null)
            {
                return NotFound();
            }
            return View(gamer);
        }

        // POST: Gamers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Surname,Name,DataRegistr,Email,Paswd,Rank")] Gamer gamer)
        {
            if (id != gamer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gamer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamerExists(gamer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gamer);
        }

        // GET: Gamers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamer = await _context.Gamer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gamer == null)
            {
                return NotFound();
            }

            return View(gamer);
        }

        // POST: Gamers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gamer = await _context.Gamer.FindAsync(id);
            if (gamer != null)
            {
                _context.Gamer.Remove(gamer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GamerExists(int id)
        {
            return _context.Gamer.Any(e => e.Id == id);
        }
    }
}

Game-master/Game/Views/Gamers/Create.cshtml
@model Gamer

@{
    ViewData["Title"] = "Создать";
}

<h1>Добавить</h1>

<h4>заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataRegistr" class="control-label"></label>
                <input asp-for="DataRegistr" class="form-control" />
                <span asp-validation-for="DataRegistr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paswd" class="control-label"></label>
                <input asp-for="Paswd" class="form-control" />
                <span asp-validation-for="Paswd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rank" class="control-label"></label>
                <input asp-for="Rank" class="form-control" />
                <span asp-validation-for="Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Game-master/Game/Views/Gamers/Delete.cshtml
@model Gamer

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удалить</h1>

<h3>Вы уверенны что хотите удалить запись?</h3>
<div>
    <h4>заказ</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRegistr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRegistr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paswd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paswd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rank)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться назад</a>
    </form>
</div>

Game-master/Game/Views/Gamers/Details.cshtml
@model Gamer

@{
    ViewData["Title"] = "Подробнее";
}

<h1>Подробнее</h1>

<div>
    <h4>Заказ</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRegistr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRegistr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paswd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paswd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rank)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Изменить</a> |
    <a asp-action="Index">Вернуться назад</a>
</div>

Game-master/Game/Views/Gamers/Edit.cshtml
@model Gamer

@{
    ViewData["Title"] = "Изменить";
}

<h1>Изменить</h1>

<h4>Заказ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataRegistr" class="control-label"></label>
                <input asp-for="DataRegistr" class="form-control" />
                <span asp-validation-for="DataRegistr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paswd" class="control-label"></label>
                <input asp-for="Paswd" class="form-control" />
                <span asp-validation-for="Paswd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rank" class="control-label"></label>
                <input asp-for="Rank" class="form-control" />
                <span asp-validation-for="Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Game-master/Game/Views/Gamers/Index.cshtml
@model Game.Models.GamerRankViewModel

@{
    ViewData["Title"] = "Заказы";
}

<h1>Заказы</h1>

<p>
    <a asp-action="Create">Добавить заказ</a>
</p>
<form asp-controller="Gamers" asp-action="Index" method="get">
    <p>
        <label>
            Поиск
            <select asp-for="GamerRank" asp-items="Model.Rank">
                <option value="">Все</option>
            </select>
        </label>

        <label>Поиск: <input type="text" asp-for="SearchString" /></label>
        <input type="submit" value="Фильтр" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().DataRegistr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().Paswd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gamers.First().Rank)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Gamers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataRegistr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paswd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rank)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">изменить</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">подробнее</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>